CREATE SCHEMA `sistema_cadastro`;
USE sistema_cadastro;
CREATE TABLE usuarios (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(40) NOT NULL,
	sobrenome VARCHAR(100),
	senha_hash VARCHAR(255) NOT NULL,
	idade INT,
	email VARCHAR(150) UNIQUE NOT NULL,
	cpf VARCHAR(14) UNIQUE NOT NULL,
	celular VARCHAR(20),
	endereço_completo VARCHAR(300),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);